name: Build All Targets

on:
  workflow_dispatch:
#permissions: write-all
env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: short

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@1.77.0

      - name: Add Rust Target
        run: rustup target add ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri
          cache-all-crates: true

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Yarn
        # You may pin to the exact commit or the version.
        # uses: mskelton/setup-yarn@15308d4b4c6e3e3ee269ec97a91d0d6bbb24ff36
        uses: mskelton/setup-yarn@v2.0.0
        with:
          # Additional flags to pass to the install command.
          #flags: # optional
          # Node version to use, defaults to the current LTS version.
          node-version: "20"
          # Git ref to checkout. Passed to `actions/checkout`.
          #ref: # optional
          # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm
          #cache: # optional, default is yarn
          # Fetch depth of the checkout. Passed to `actions/checkout`.
          #fetch-depth: # optional

      - name: install node packages
        run: yarn install

      - name: build
        run: yarn tauri build
